---

- name: install certbot
  apt:
    name: certbot
    state: present

- name: install letsencrypt hook
  copy:
    src: hook.sh
    dest: /etc/letsencrypt/hook.sh
    owner: root
    group: root
    mode: 0755

- name: create letsencrypt hook dir
  file:
    state: directory
    path: /etc/letsencrypt/hook.d
    owner: root
    group: root
    mode: 0755

- name: install letsencrypt renewal service
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - certbot-renewal.service
    - certbot-renewal.timer

- name: activate letsencrypt renewal service
  systemd:
    name: certbot-renewal.timer
    enabled: yes
    state: started
    daemon_reload: yes
