#                                     __
#                                    / _|
#   __ _ _   _ _ __ ___  _ __ __ _  | |_ ___  ___ ___
#  / _` | | | | '__/ _ \| '__/ _` | |  _/ _ \/ __/ __|
# | (_| | |_| | | | (_) | | | (_| | | || (_) \__ \__ \
#  \__,_|\__,_|_|  \___/|_|  \__,_| |_| \___/|___/___/
#
# Copyright (C) 2020 Aurora Free Open Source Software.
# Copyright (C) 2020 Luís Ferreira <luis@aurorafoss.org>
#
# This file is part of the Aurora Free Open Source Software. This
# organization promote free and open source software that you can
# redistribute and/or modify under the terms of the Boost Software License
# Version 1.0 available in the package root path as 'LICENSE' file. Please
# review the following information to ensure that the license requirements
# meet the opensource guidelines at opensource.org .
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
# NOTE: All products, services or anything associated to trademarks and
# service marks used or referenced on this file are the property of their
# respective companies/owners or its subsidiaries. Other names and brands
# may be claimed as the property of others.
#
# For more info about intellectual property visit: aurorafoss.org or
# directly send an email to: contact (at) aurorafoss.org .


version: "3.7"
services:
  web:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./webapp/:/var/www/html/:ro
      - ./config/contrib/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/contrib/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - "php-fpm:php-fpm.docker.local"
      - "websocket:websocket.docker.local"
    depends_on:
      - php-fpm
      - database
      - websocket
  websocket:
    build: ./config/docker/context/node
    restart: unless-stopped
    user: ${CURRENT_UID}
    working_dir: /home/node/app
    volumes:
      - ./websockets/:/home/node/app
  php-fpm:
    restart: unless-stopped
    image: aurorafossorg/php-fpm:latest
    build: ./config/docker/context/php-fpm
    volumes:
      - ./webapp/:/var/www/html/
    links:
      - "database:db.docker.local"
    depends_on:
      - database
    user: ${CURRENT_UID}
  database:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - .php-devenv/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mardb
      MYSQL_DATABASE: sql_db1
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user
  adminer:
    image: adminer
    restart: unless-stopped
    links:
      - "database:db.docker.local"
    ports:
      - "10000:8080"
    depends_on:
      - database
